# Generated by Django 5.0.7 on 2024-10-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyque_app', '0004_rename_is_admin_user_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_phone_verified',
            new_name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
