# Generated by Django 5.0.7 on 2024-10-18 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyque_app', '0007_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyque_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyque_app.user')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
