# Generated by Django 5.0.7 on 2024-10-21 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyque_app', '0008_shortlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortlist',
            old_name='created_at',
            new_name='added_on',
        ),
        migrations.AlterUniqueTogether(
            name='shortlist',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='shortlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by', to='babyque_app.product'),
        ),
        migrations.AlterField(
            model_name='shortlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlist', to='babyque_app.user'),
        ),
    ]
