# Generated by Django 5.0.7 on 2024-10-22 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyque_app', '0009_rename_created_at_shortlist_added_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortlist',
            old_name='added_on',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='shortlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyque_app.product'),
        ),
        migrations.AlterField(
            model_name='shortlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='shortlist',
            unique_together={('user', 'product')},
        ),
    ]
