# Generated by Django 5.0.7 on 2024-10-22 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyque_app', '0010_rename_added_on_shortlist_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortlist',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='shortlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by', to='babyque_app.product'),
        ),
        migrations.AlterField(
            model_name='shortlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyque_app.user'),
        ),
    ]
