# Generated by Django 5.0.7 on 2024-10-24 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyque_app', '0011_remove_shortlist_created_at_alter_shortlist_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyque_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyque_app.user')),
            ],
        ),
    ]
