# Generated by Django 5.0.7 on 2024-10-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyque_app', '0020_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='processing', max_length=20),
        ),
    ]
